export const REQUEST_PROFILE_DETAIL = "app/profile/REQUEST_JOB_DETAIL"
export const REQUEST_PROFILE_DETAIL_SUCCESS = "app/profile/REQUEST_PROFILE_DETAIL_SUCCESS"

export const REQUEST_CANDIDATE_DETAIL_SUCCESS = "app/profile/REQUEST_CANDIDATE_DETAIL_SUCCESS"

export const UPDATE_EDUCATION_LIST_CANDIDATE = "app/profile/UPDATE_EDUCATION_LIST_CANDIDATE"

export const UPDATE_EXPERIENCE_LIST_CANDIDATE = "app/profile/UPDATE_EXPERIENCE_LIST_CANDIDATE"

export const UPDATE_PROJECT_LIST_CANDIDATE = "app/profile/UPDATE_PROJECT_LIST_CANDIDATE"

export const UPDATE_SKILL_LIST_CANDIDATE = "app/profile/UPDATE_SKILL_LIST_CANDIDATE"

export const UPDATE_PROFILE_CANDIDATE = "app/profile/UPDATE_PROFILE_CANDIDATE"

export const UPDATE_INTEREST_CANDIDATE = "app/profile/UPDATE_INTEREST_CANDIDATE"

export const UPDATE_LOOKING_CANDIDATE = "app/profile/UPDATE_LOOKING_CANDIDATE"

export const UPDATE_SUMMARY_CANDIDATE = "app/profile/UPDATE_SUMMARY_CANDIDATE"

export const UPDATE_COVER_LETTER_CANDIDATE = "app/profile/UPDATE_COVER_LETTER_CANDIDATE"

export const UPDATE_CV_CANDIDATE = "app/profile/UPDATE_CV_CANDIDATE"

export const UPDATE_AVATAR_CANDIDATE = "app/profile/UPDATE_AVATAR_CANDIDATE"

export const LOOKING_STATUS_CANDIDATE = "app/profile/LOOKING_STATUS_CANDIDATE"

export const UPDATE_AVATAR_EMPLOYER = "app/profile/UPDATE_AVATAR_EMPLOYER"